#!/bin/bash
wget --spider http://www.baidu.com 1>/dev/null 2>/dev/null
while [ "$?" != 0 ];
do
        sleep 5;
        wget --spider http://www.baidu.com 1>/dev/null 2>/dev/null
done

export DISPLAY=:0.0

sed -i 's/"exited_cleanly": false/"exited_cleanly": true/' ~/.config/chromium/Default/Preferences

chromium-browser &
xdpms
sleep 5

refresh
