#!/bin/bash
sleep 5

cont=0;
while true;
do

echo "ready to start scan"
uuid=`nmcli con list | grep 3GNet | awk  '{print $2}'`

LC_ALL=C nmcli -t -f TYPE,STATE dev | grep -q "^gsm:disconnected$"
if [ $? -eq 0 ]; then
	timeout 10 nmcli -t con up uuid $uuid
	let cont=$cont+1
	echo $cont

	if [ $cont -gt 2 ] ;then
		echo "ready to restart Network"
		sudo restartNetwork
		sleep 2 

		cont=0;
	fi
fi
sleep 4
done
